[Fix] Accuracy changed from array to float
shift-happens-benchmark/icml-2022 pull request #101
Opened 2022-08-16 16:16 UTC by kotekjedi

2022-08-16 16:17 UTC, kotekjedi commented on shifthappens/tasks/imagenet_r/imagenet_r.py
> +    )
```suggestion
        )
```

2022-08-28 14:15 UTC, zimmerrol requested changes
Thanks for this PR. Can you please explain why you propose these changes/what they are meant to fix?

2022-08-28 14:15 UTC, zimmerrol commented on shifthappens/tasks/imagenet_c/imagenet_c.py
> +            accuracy=np.mean(np.array(accuracies)),
That doesn't look right, as we already take the mean in L102.

2022-08-28 14:20 UTC, kotekjedi commented on shifthappens/tasks/imagenet_c/imagenet_c.py
> +            accuracy=np.mean(np.array(accuracies)),
Here `accuracies` is an array of the accuracy values for every task. So we take the mean of these accuracies in L452.

2022-08-28 14:24 UTC, kotekjedi commented
@zimmerrol At the moment, in L105, `accuracy` is an array of True and False values. I think it is a bug because we require the `metrics` field in `TaskResult` to be a `**metrics: Union[float, int]`.

2022-09-06 21:12 UTC, zimmerrol approved these changes

2022-09-06 21:25 UTC, merged