Extend API documentation
shift-happens-benchmark/icml-2022 pull request #29
Opened 2022-05-02 11:53 UTC by stes

- Remove the duplicate "optional" classifiers currenlty in the text, this is done automatically by sphinx
- Remove the "temporary" note from `api.rst`
- Add more verbose descriptions to the task

2022-05-02 11:55 UTC, stes commented
Ok there's some overlap with #28 , but the other changes still apply. Also, reordered the docs in ``api.rst`` to make the tasks appear first, which is more relevant for users. I excluded the torchvision models for now, as these do not contain any public classes yet.

2022-05-02 12:51 UTC, zimmerrol commented
Let's first merge #28 before reviewing and merging this one.

2022-05-02 12:54 UTC, zimmerrol requested changes

2022-05-02 12:54 UTC, zimmerrol commented on shifthappens/tasks/base.py
> +    ``shifthappens.models.base.ModelResult`` returned during evaluation.
This should be changed to something like:

    :py:class:`shifthappens.models.base.ModelResult`

to make sure sphinx uses the correct links to the respective class documentations.

The same also applies to tall other occurences.

2022-05-02 13:46 UTC, stes commented on shifthappens/tasks/base.py
> +    ``shifthappens.models.base.ModelResult`` returned during evaluation.
done (hope I got all of them)

2022-05-02 13:47 UTC, stes commented
@zimmerrol cross refs are fixed, hope I didnt miss any

2022-05-02 13:47 UTC, stes commented
Also, this is rebased onto #28 now, I'll change base branch for a better diff. Please merge #28 first, then merge this one.

2022-05-02 13:58 UTC, zimmerrol commented
Once you've reviewed #28 I can merge both PRs.

2022-05-02 14:00 UTC, zimmerrol commented on shifthappens/tasks/base.py
> +        model: The passed model implementents a ``predict`` function returning an iterator
Let's also use the same docstring style as for the rest, i.e.:

    Args:
        model: The passed model ...

2022-05-02 14:11 UTC, stes commented
> We could improve one small thing regarding docstring-styles about this PR before merging it.

we'll use [google style doc strings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), right?

2022-05-02 15:12 UTC, zimmerrol commented
Yep, that is correct. I think only at one location (see my comment above) you used a different style.

2022-05-03 18:24 UTC, zimmerrol approved these changes
LGTM

2022-05-03 18:52 UTC, merged