imagenet 3dcc example
shift-happens-benchmark/icml-2022 pull request #52
Opened 2022-06-22 12:51 UTC by aserety

# Task Description

We introduce a set of image transformations that can be used as corruptions to evaluate the robustness of models. The primary distinction of the proposed transformations is that, unlike existing approaches such as Common Corruptions [1], the geometry of the scene is incorporated in the transformations – thus leading to corruptions that are more likely to occur in the real world. We apply these corruptions to the ImageNet validation set to create 3D Common Corruptions (ImageNet-3DCC) benchmark. Some examples are shown below.

![pull_imagenet](https://user-images.githubusercontent.com/9682590/175020233-e303bdd4-7e4f-4eab-a745-dff6a2b26780.jpg) 

## Dataset Creation

Most of the corruptions require an RGB image and scene depth, except the noise ones that can be generated from RGB image directly. As ImageNet images do not have depth labels, we generate depth predictions using a state-of-the-art depth estimator [2,3]. We described the methods used to generate the corruptions in the main paper and in [3]. 

## Evaluation Metrics

We use the mean Corruption Error as defined in [1]. It is relevant as we also defined five levels of shift intensities for each corruption.

## Expected Insights/Relevance

3DCC incorporates 3D information to generate corruptions that are consistent with the scene geometry. This leads to shifts that are more likely to occur in the real world. We expect to gain insights to model vulnerabilities under real-world plausible corruptions that are not captured by 2D corruptions.

# Access

## Data

Instructions for downloading the entire dataset can be found [here](https://github.com/EPFL-VILAB/3DCommonCorruptions#3dcc-data). Alternatively, to download individual corruptions, the link is given by `https://datasets.epfl.ch/3dcc/imagenet_3dcc/x.tar.gz` where x is the name of the corruption i.e. `x=[near_focus,far_focus,fog_3d,flash,color_quant,low_light,xy_motion_blur,z_motion_blur,iso_noise,bit_error,h265_abr,h265_crf]`.

## License

Yes, we have the permission to release the images.

----
[1] Hendrycks et al., Benchmarking Neural Network Robustness to Common Corruptions and Perturbations, ICLR'19.
[2] Eftekhar et al., Omnidata: A scalable pipeline for making multi-task mid-level vision datasets from 3d scans, ICCV'21.
[3] Kar et al., 3d common corruptions and data augmentation, CVPR'22.

2022-06-23 14:00 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"color_quant"` is provided, `"tmp"` is not necessary.

2022-06-23 14:00 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"low_light"` is provided, `"tmp"` is not necessary.

2022-06-23 14:00 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"xy_motion_blur"` is provided, `"tmp"` is not necessary.

2022-06-23 14:00 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"z_motion_blur"` is provided, `"tmp"` is not necessary.

2022-06-23 14:00 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"iso_noise"` is provided, `"tmp"` is not necessary.

2022-06-23 14:00 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"bit_error"` is provided, `"tmp"` is not necessary.

2022-06-23 14:01 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"h265_abr"` is provided, `"tmp"` is not necessary.

2022-06-23 14:02 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +    """Classification task on the ImageNet-C dataset where models might use all images
Should it be `Classification task on the ImageNet-3DCC dataset...`?

2022-06-23 14:03 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +            "tmp",
Since folder `"h265_crf"` is provided, `"tmp"` is not necessary.

2022-06-23 14:03 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +    name="ImageNet-3DCC", relative_data_folder="imagenet_3dcc", standalone=False
It should be `standalone=True`.

2022-06-23 14:05 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +        (ImageNet3DCCFarFocus,)
I think all corruptions should be added here?
Something like : 
```
 corruption_task_cls: Tuple[Type[ImageNetSingleCorruptionTypeBase], ...] = variable(
        (
            ImageNet3DCCNearFocus,
            ImageNet3DCCFarFocus,
            ImageNet3DCCFog3D,
            ImageNet3DCCFlash,
            ImageNet3DCCColorQuant,
            ImageNet3DCCLowLight,
            ImageNet3DCCXYMotionBlur,
            ImageNet3DCCZMotionBlur,
            ImageNet3DCCISONoise,
            ImageNet3DCCBitError,
            ImageNet3DCCH256ABR,
            ImageNet3DCCH256CRF,
        )
    )
```

2022-06-23 14:05 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +    from shifthappens.models.torchvision import resnet18, resnet50
It should be    `from shifthappens.models.torchvision import ResNet18, ResNet50`.

2022-06-23 14:07 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +    # sh_benchmark.evaluate_model(resnet18(device="cuda",max_batch_size=2048), "test_data")
I think it would be enough to leave in the main only one line, e.g. `sh_benchmark.evaluate_model(ResNet18(max_batch_size=128), "test_data")`

2022-06-23 14:17 UTC, kotekjedi commented
Hi, Teresa!
My name is Alexander Panfilov; I am a student research assistant working on supporting the project. I reviewed the PR, and since it requires only tiny fixes, I'd like to offer you that I will fix these issues myself (if you are OK with suggested changes).

What do you think?

2022-06-23 16:58 UTC, aserety commented
Hi Alexander,
Yes, you can go ahead and fix them. The changes looks good. Thanks for offering! :)
Teresa

2022-07-09 20:55 UTC, stes reviewed
Resolved the open comment.

2022-07-09 20:55 UTC, stes commented on examples/imagenet_3dcc.py
> +            sh_utils.download_and_extract_archive(
I think this was addressed, closing.

2022-07-09 20:57 UTC, stes commented
Hi @kotekjedi, I think you made some changes to this PR. Could you resolve all comments you already addressed, and report what the status on this PR is?

2022-07-09 22:00 UTC, stes requested changes
Hi @aserety, thanks a lot for your contribution. We are working towards the first release of the benchmark and for this, released our [contribution guide](https://github.com/shift-happens-benchmark/icml-2022/blob/main/CONTRIBUTING.rst) with the aim of unifying the implementation of all contributions.

Please have a look, the required changes should be relatively small and are mostly concerns with placing the files within the package, and adding documentation.

From reviewing your PR, the main required changes are:

- [ ] Place the files into their own package inside the `tasks/` folder (@georgepachitariu )
- [ ] Add a README and optionally citation info
- [ ] We are also looking into the best ways to perform unit or integration tests and would be happy to get some feedback on how this would be most effective for you benchmark. Would it be possible to add a "dry-run/demo" option to the benchmark, and e.g. run it only on a small subset of the data? No immediate action/update is required right now, we are first gathering opinions from all authors on this.

Thanks a lot for your contribution, and please ping me if you have any questions. If you have technical questions, also feel free to ping @kotekjedi who is happy to help with implementation details.

2022-07-09 22:00 UTC, stes commented on examples/imagenet_3dcc.py
> +class ImageNet3DCCNearFocus(ImageNetSingleCorruptionTypeBase):
Also for the subclasses, docstrings would be great.

2022-07-09 22:00 UTC, stes commented on examples/imagenet_3dcc.py
> +    results = sh_benchmark.evaluate_model(ResNet18(max_batch_size=128), "test_data")
```suggestion
```

This can be removed once added to the tasks. Feel free to add a test function to your package, though!

2022-07-10 05:56 UTC, stes commented
Hi!

This is an automated report for the documentation coverage of your PR. To provide good user experience for the benchmark, we aim to cover most functions with doc strings, using the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

We would greatly appreciate your help in assuring that docstring coverage is sufficiently high for your contribution.

The current coverage is:
| Name                                 |   Total |   Miss |   Cover |   Cover% |
|--------------------------------------|---------|--------|---------|----------|
| examples/imagenet_3dcc.py            |      17 |     15 |       2 |      12% |
| shifthappens/models/torchvision.py   |       4 |      0 |       4 |     100% |
|--------------------------------------|---------|--------|---------|----------|
| TOTAL                                |      21 |     15 |       6 |    28.6% |
RESULT: FAILED (minimum: 80.0%, actual: 28.6%)

You can reproduce this result by running

```
interrogate -v --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method
```

on the files you added to your PR.

2022-08-03 08:32 UTC, kotekjedi commented on examples/imagenet_3dcc.py
> +"""Shift Happens task for ImageNet-3DCC
Should we maybe delete this file from the PR since we moved everything to the tasks?

2022-08-03 21:08 UTC, aserety commented on examples/imagenet_3dcc.py
> +"""Shift Happens task for ImageNet-3DCC
Yep, Ive removed it :)

2022-08-15 14:25 UTC, ofkar commented
Hi @stes @kotekjedi  is there anything else needed from our side? @aserety made the requested changes, please let us know if it looks good to you. Thanks!

2022-08-15 19:13 UTC, kotekjedi reviewed
Hi! I suggested some fixes to pass `black `and `mypy` linters.

2022-08-15 19:13 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +        )
```suggestion
        accuracy = np.equal(
            all_predicted_labels,
            np.array(self.ch_dataset.targets)[: len(all_predicted_labels)],
        ).mean()
```
to pass mypy

2022-08-15 19:13 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +            mce=np.mean(mces).item(),
```suggestion
            accuracy=np.mean(np.array(accuracies)),
            mce=np.mean(np.array(mces)),
```
to pass mypy

2022-08-15 19:51 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion
            summary_metrics={Metric.Robustness: "accuracy"},
        )
```

2022-08-15 19:56 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 19:56 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 19:56 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 19:56 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 19:56 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 19:56 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 19:56 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 19:57 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 20:01 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 20:01 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 20:01 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 20:01 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion

```

2022-08-15 20:02 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion
            summary_metrics={Metric.Robustness: "accuracy"},
        )
```

2022-08-15 20:03 UTC, kotekjedi commented on shifthappens/tasks/imagenet_3dcc/imagenet_3dcc.py
> +
```suggestion
        return TaskResult(
            **results,
            accuracy=np.mean(np.array(accuracies)),
            mce=np.mean(np.array(mces)),
            summary_metrics={Metric.Robustness: "accuracy"},
        )
```

2022-11-19 10:14 UTC, zimmerrol approved these changes

2022-11-19 10:14 UTC, merged