Add SISCORE dataset.
shift-happens-benchmark/icml-2022 pull request #59
Opened 2022-06-27 08:12 UTC by jessicayung

([Dataset homepage](https://github.com/google-research/si-score))

# Task Description

As we begin to bring image classification models into the real world, it is important that they are robust and do not overfit to academic datasets. While robustness is hard to define, one can think of intuitive factors that image classification models should be robust to, such as changes in object location or differing weather conditions. Models should at least be robust to these factors. To test this, ideally we would have datasets that vary only these factors. For some factors such as image compression and differing weather conditions, datasets such as Imagenet-C already exist, whereas for common-sense factors such as object size and object location, such datasets did not yet exist prior to SI-SCORE.

In SI-SCORE, we take objects and backgrounds and systematically vary object size, location and rotation angle so we can study the effect of changing these factors on model performance. We also provide the code, object images and background images and hope that researchers can create their own datasets to test robustness to other factors of variation.

Here are some sample images from the dataset:

<img src="https://raw.githubusercontent.com/google-research/si-score/master/sample_images/demo_img_koala_default_big_2.jpg" width="200"> <img src="https://raw.githubusercontent.com/google-research/si-score/master/sample_images/demo_img_koala_loc_23_2.jpg" width="200"> <img src="https://raw.githubusercontent.com/google-research/si-score/master/sample_images/demo_img_koala_rotate_50_2.jpg" width="200">

<img src="https://raw.githubusercontent.com/google-research/si-score/master/sample_images/demo_img_koala_default.jpg" width="200"> <img src="https://raw.githubusercontent.com/google-research/si-score/master/sample_images/demo_img_koala_loc_76.jpg" width="200"> <img src="https://raw.githubusercontent.com/google-research/si-score/master/sample_images/demo_img_koala_rotate_230.jpg" width="200">

## Dataset Creation

## Evaluation Metrics
The dataset uses accuracy as an evaluation metric. One can also calculate the accuracy per e.g. object size to compare model performance across different object sizes (/locations of the object in the image / object rotation angles).

## Expected Insights/Relevance
Discovering differences in robustness to changes in object size/location/rotation angle between image classification models, such as ResNet-50s with GroupNorm being better at classifying small objects than ResNet-50s with BatchNorm. (See [our workshop paper](https://arxiv.org/abs/2104.04191) for more details.)

Testing hypotheses such as whether Vision Transformer models perform worse when objects are on patch intersections.

# Access

## Data

[Dataset homepage](https://github.com/google-research/si-score)
Big zip files: `https://s3.us-east-1.amazonaws.com/si-score-dataset/{rotation|location|area}.zip`

## License
Yes - Apache 2.0 license.

2022-07-09 21:11 UTC, stes requested changes
Hi @jessicayung , thanks a lot for your contribution. We are working towards the first release of the workshop and for this, released our [contribution guide](https://github.com/shift-happens-benchmark/icml-2022/blob/main/CONTRIBUTING.rst) with the aim of unifying the implementation of all contributions.

Please have a look, the required changes should be relatively small and are mostly concerns with placing the files within the package, and adding documentation.

From reviewing your PR, the main required changes are:

- [ ] Place the files into their own package inside the `tasks/` folder
- [ ] Add a README and optionally citation info
- [ ] We are also looking into the best ways to perform unit or integration tests and would be happy to get some feedback on how this would be most effective for you benchmark. Would it be possible to add a "dry-run/demo" option to the benchmark, and e.g. run it only on a small subset of the data? No immediate action/update is required right now, we are first gathering opinions from all authors on this.

Thanks a lot for your contribution, and please ping me if you have any questions. If you have technical questions, also feel free to ping @kotekjedi who is happy to help with implementation details.

2022-07-10 05:56 UTC, stes commented
Hi!

This is an automated report for the documentation coverage of your PR. To provide good user experience for the benchmark, we aim to cover most functions with doc strings, using the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

We would greatly appreciate your help in assuring that docstring coverage is sufficiently high for your contribution.

The current coverage is:
| Name                         |     Total |     Miss |     Cover |     Cover% |
|------------------------------|-----------|----------|-----------|------------|
| models/torchvision.py        |         4 |        0 |         4 |       100% |
| tasks/siscore.py             |         8 |        5 |         3 |        38% |
| tasks/siscore_labels.py      |         1 |        0 |         1 |       100% |
|------------------------------|-----------|----------|-----------|------------|
| TOTAL                        |        13 |        5 |         8 |      61.5% |
RESULT: FAILED (minimum: 80.0%, actual: 61.5%)

You can reproduce this result by running

```
interrogate -v --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method
```

on the files you added to your PR.

2022-07-21 02:58 UTC, stes commented
@kotekjedi could you run the pre-commit hooks on this PR so that we pass the first test?

2022-08-02 11:54 UTC, kotekjedi reviewed
Changes to pass `isort` test

2022-08-02 11:54 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +import siscore_labels
```suggestion
```

2022-08-02 11:54 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +import numpy as np
```suggestion
import numpy as np
import siscore_labels
```

2022-08-02 22:40 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +        # TODO(jessicayung): return more fine-grained metric as well,
Should we remove this TODO?

2022-08-15 19:22 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +    standalone=False,
```suggestion
    standalone=True,
```

2022-08-15 19:22 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +    standalone=False,
```suggestion
    standalone=True,
```

2022-08-15 19:22 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +    standalone=False,
```suggestion
    standalone=True,
```

2022-08-15 19:35 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +import siscore_labels
```suggestion
```

2022-08-15 19:35 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +    resource: Tuple[str, ...] = variable(("rotation"))
```suggestion
class SISCORERotation(SISCOREVariantBase):
    """Various rotations subset."""
    
    resource: Tuple[str, ...] = variable(("rotation"))
```

2022-08-15 19:40 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +
```suggestion

```

2022-08-15 19:40 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +
```suggestion

```

2022-08-15 19:40 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +
```suggestion

```

2022-08-15 19:46 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +    """Various object size subset."""
```suggestion
    """Various object size subset."""

```

2022-08-15 19:46 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +    """Various rotations subset."""
```suggestion
    """Various rotations subset."""

```

2022-08-15 19:46 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +    """Various locations subset."""
```suggestion
    """Various locations subset."""

```

2022-09-25 11:56 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +        # i.e. accuracy per object size/rotation angle etc.
```suggestion
        
```

2022-09-25 11:56 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +        # TODO(jessicayung): return more fine-grained metric as well,
```suggestion
```

2022-09-25 12:02 UTC, kotekjedi commented on shifthappens/tasks/siscore/siscore.py
> +
```suggestion
```

2022-11-17 21:06 UTC, zimmerrol approved these changes

2022-11-17 21:06 UTC, merged