WIP: ImageNet-Patch dataset
shift-happens-benchmark/icml-2022 pull request #60
Opened 2022-06-27 09:37 UTC by maurapintor

# Task Description
A dataset for benchmarking machine learning robustness against adversarial patches, based on the ImageNet dataset and adversarial patch attacks.

![image](https://user-images.githubusercontent.com/23276849/175907315-fb8ddf46-23c7-461f-870a-7f09638c98ae.png)

## Dataset Creation
Images are taken from the ImageNet dataset. The ten optimized patches proposed in the paper are then applied to such images to create the perturbed data.
The patch optimization follows [1].

[1] https://arxiv.org/abs/1712.09665

![image](https://user-images.githubusercontent.com/23276849/175907709-7bd272e1-1808-432b-a7ca-ebe083d9a5da.png)

## Evaluation Metrics

- Robust accuracy: correct classification of the images with the applied patch.

## Expected Insights/Relevance

This dataset was designed to measure the robustness of the models to the application of adversarial patches. Adding this test can give further insights on robustness of the model as a general property, beyond the evaluation that is usually performed against one specific perturbation bound (e.g., $L_\infty$ norm with maximum size of 8/255)

## Access

We release the dataset on Zenodo (https://zenodo.org/record/6568778), as well as the code to generate patches and to apply them dynamically to custom images (https://github.com/pralab/ImageNet-Patch).

## Data

The dataset is hosted on Zenodo: https://zenodo.org/record/6568778

## License

We released the data with the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/legalcode).

2022-07-09 21:24 UTC, stes requested changes
Hi @maurapintor, thanks a lot for your contribution. We are working towards the first release of the benchmark and for this, released our [contribution guide](https://github.com/shift-happens-benchmark/icml-2022/blob/main/CONTRIBUTING.rst) with the aim of unifying the implementation of all contributions.

Please have a look, the required changes should be relatively small and are mostly concerned with placing the files within the package, and adding documentation.

From reviewing your PR, the main required changes are:

- [ ] Place the files into their own package inside the `tasks/` folder
- [ ] Adding a docstring to your package (this will be rendered in the documentation)
- [ ] Add a README and optionally citation info
- [ ] We are also looking into the best ways to perform unit or integration tests and would be happy to get some feedback on how this would be most effective for you benchmark. Would it be possible to add a "dry-run/demo" option to the benchmark, and e.g. run it only on a small subset of the data? No immediate action/update is required right now, we are first gathering opinions from all authors on this.

Thanks a lot for your contribution, and please ping me if you have any questions. If you have technical questions, also feel free to ping @kotekjedi who is happy to help with implementation details.

2022-07-09 21:24 UTC, stes commented on examples/imagenet_patch.py
> +import dataclasses
A docstring here would be great.

2022-07-09 21:24 UTC, stes commented on examples/imagenet_patch.py
> +class ImageNetPatchTarget(Task):
Also here, a docstring would be nice

2022-07-09 21:24 UTC, stes commented on examples/imagenet_patch.py
> +class ImageNetPatchCellularTelephone(ImageNetPatchTarget):
Short docstrings for each class (as they appear in the documentation) would be nice.

2022-07-10 05:55 UTC, stes commented
Hi!

This is an automated report for the documentation coverage of your PR. To provide good user experience for the benchmark, we aim to cover most functions with doc strings, using the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

We would greatly appreciate your help in assuring that docstring coverage is sufficiently high for your contribution.

The current coverage is:
| Name                                 |   Total |   Miss |   Cover |   Cover% |
|--------------------------------------|---------|--------|---------|----------|
| examples/imagenet_patch.py           |      15 |     14 |       1 |       7% |
| shifthappens/models/torchvision.py   |       4 |      0 |       4 |     100% |
|--------------------------------------|---------|--------|---------|----------|
| TOTAL                                |      19 |     14 |       5 |    26.3% |
RESULT: FAILED (minimum: 80.0%, actual: 26.3%)

You can reproduce this result by running

```
interrogate -v --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method
```

on the files you added to your PR.

2022-07-18 17:01 UTC, maurapintor commented on shifthappens/tasks/imagenet_patch/__main__.py
> +        self.ch_dataset = tv_datasets.ImageFolder(
Yes, it makes sense. Thanks!

2022-09-06 08:41 UTC, kotekjedi commented on shifthappens/tasks/imagenet_patch/imagenet_patch.py
> +        accuracy = all_preds == np.array(self.ch_dataset.targets)[: len(all_preds)]
```suggestion
        accuracy = (all_preds == np.array(self.ch_dataset.targets)[: len(all_preds)]).mean()
```

2022-09-06 08:49 UTC, kotekjedi commented
Hello Maura!
Could you please check "Allow edits from maintainers" so it would be possible for us to add minor fixes to PR before merging?

2022-09-06 09:10 UTC, maurapintor commented
> Hello Maura!
> Could you please check "Allow edits from maintainers" so it would be possible for us to add minor fixes to PR before merging?

Thank you @kotekjedi!
I checked the box, now maintainers should be able to apply edits.

2022-11-17 21:08 UTC, merged