Proposed task in worst_case.py
shift-happens-benchmark/icml-2022 pull request #63
Opened 2022-06-27 16:14 UTC by valentyn1boreiko

# Task Description
This task evaluates a set of metrics, mostly related to worst-class performance, as described in
(J. Bitterwolf et al., "Classifiers Should Do Well Even on Their Worst Classes", https://openreview.net/forum?id=QxIXCVYJ2WP).
It is motivated by
(R. Balestriero et al., "The Effects of Regularization and Data Augmentation are Class Dependent", https://arxiv.org/abs/2204.03632)
 where the authors note that using only accuracy as a metric is not enough to evaluate
 the performance of the classifier, as it must not be the same on all classes/groups.

## How to start
run
python examples/worst_case.py --imagenet_val_folder '/scratch/datasets/imagenet/val' --verbose --labels_type 'val'
for evaluating with original labels, and
python examples/worst_case.py --imagenet_val_folder '/scratch/datasets/imagenet/val' --verbose --labels_type 'val_clean'
for evaluating with cleaned ones from (C. Northcutt et al., "Pervasive Label Errors in Test Sets Destabilize Machine Learning Benchmarks", https://arxiv.org/abs/2103.14749, https://github.com/cleanlab/label-errors)
## Dataset Creation
No dataset has been created.

## Evaluation Metrics
The evaluation metrics are "A", "WCA", "WCP", "WSupCA", "WSupCR",  "W10CR", "W100CR", "W2CA", "WCAat5", "W10CRat5", "W100CRat5", and their relevance is described in (J. Bitterwolf et al., "Classifiers Should Do Well Even on Their Worst Classes", https://openreview.net/forum?id=QxIXCVYJ2WP).

## Expected Insights/Relevance
To see the, how the model performs on its worst classes. The application examples are given in (J. Bitterwolf et al., "Classifiers Should Do Well Even on Their Worst Classes", https://openreview.net/forum?id=QxIXCVYJ2WP).

# Access

## Data
No dataset has been added.

## License
No dataset has beed created.

2022-07-09 21:19 UTC, stes requested changes
Hi @valentyn1boreiko, thanks a lot for your contribution. We are working towards the first release of the benchmark and for this, released our [contribution guide](https://github.com/shift-happens-benchmark/icml-2022/blob/main/CONTRIBUTING.rst) with the aim of unifying the implementation of all contributions.

Please have a look, the required changes should be relatively small and are mostly concerns with placing the files within the package, and adding documentation.

From reviewing your PR, the main required changes are:

- [ ] Place the files into their own package inside the `tasks/` folder
- [ ] Add a README and optionally citation info
- [ ] Since the benchmark contains several metrics, it would be great to add docstrings with more details on these metrics. Note that all public methods will be later rendered in the official benchmark documentation. Optionally, please also free to use more expressive variable names to make it easier for the user later on to understand the API of your task.
- [ ] We are also looking into the best ways to perform unit or integration tests and would be happy to get some feedback on how this would be most effective for you benchmark. Would it be possible to add a "dry-run/demo" option to the benchmark, and e.g. run it only on a small subset of the data? No immediate action/update is required right now, we are first gathering opinions from all authors on this.

Thanks a lot for your contribution, and please ping me if you have any questions. If you have technical questions, also feel free to ping @kotekjedi who is happy to help with implementation details.

2022-07-09 21:19 UTC, stes commented on examples/worst_case.py
> +"""
```suggestion
"""<Please add your title here -- this will be rendered in the docs>
This task evaluates a set of metrics, mostly related to worst-class performance, as described in
(J. Bitterwolf et al., "Classifiers Should Do Well Even on Their Worst Classes", https://openreview.net/forum?id=QxIXCVYJ2WP).
It is motivated by
(R. Balestriero et al., "The Effects of Regularization and Data Augmentation are Class Dependent", https://arxiv.org/abs/2204.03632)
 where the authors note that using only accuracy as a metric is not enough to evaluate
 the performance of the classifier, as it must not be the same on all classes/groups.
"""
```

Also, ideally format the docstring using RST syntax (e.g. right now, the links will not render properly in the documentation). Thanks :)

2022-07-09 21:19 UTC, stes commented on examples/worst_case.py
> +class WorstCase(Task):
Could you add a docstring to your task?

2022-07-09 21:19 UTC, stes commented on examples/worst_case.py
> +        return confusion
For all custom metrics, it would be great to have short docstrings explaining the metrics.

2022-07-09 21:20 UTC, stes commented on examples/worst_case.py
> +    def worst_balanced_n_classes_topk_accuracy(self, n, k):
For this and also other public methods, it would be great if you could rename the variables (and optionally type annotate) to make it easier to understand and use for benchmark users. Thanks!

2022-07-10 05:55 UTC, stes commented
Hi!

This is an automated report for the documentation coverage of your PR. To provide good user experience for the benchmark, we aim to cover most functions with doc strings, using the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

We would greatly appreciate your help in assuring that docstring coverage is sufficiently high for your contribution.

The current coverage is:
| Name                                 |   Total |   Miss |   Cover |   Cover% |
|--------------------------------------|---------|--------|---------|----------|
| examples/worst_case.py               |      23 |     22 |       1 |       4% |
| shifthappens/models/torchvision.py   |       4 |      0 |       4 |     100% |
|--------------------------------------|---------|--------|---------|----------|
| TOTAL                                |      27 |     22 |       5 |    18.5% |
RESULT: FAILED (minimum: 80.0%, actual: 18.5%)

You can reproduce this result by running

```
interrogate -v --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method
```

on the files you added to your PR.

2022-07-19 04:07 UTC, valentyn1boreiko commented on examples/worst_case.py
> +"""
Hi @stes, I've tried to incorporate all the changes - are they fine like this? :)

2022-07-19 04:08 UTC, valentyn1boreiko commented on examples/worst_case.py
> +"""
As for the unit testing, @stes, yes, we could easily evaluate metrics on the subset of points, but the main time is taken by the computation of the logins currently, I think, which is still not displayed using shifthappens.config.verbose = args.verbose.

2022-08-03 09:39 UTC, kotekjedi commented on examples/worst_case.py
> +        return confusion
I would like to suggest moving functions that calculate some metrics to another file, e.g. worst_class_utils.py, to make task class easier to read.

Also it would be nice to change `def func_name(self) -> np.float` to `def func_name(self) -> np.float64` to avoid numpy deprecated warnings.

2022-08-04 19:16 UTC, valentyn1boreiko commented on shifthappens/tasks/worst_case/worst_case.py
> +if __name__ == "__main__":
We could, but how one can run it then? I.e., do the users need to write their own main function, or there will be one in some main file of the repository?

2022-08-04 19:16 UTC, valentyn1boreiko commented on shifthappens/tasks/worst_case/worst_case.py
> +            erroneous_c = (preds["predicted_classes"] == c) * (self.new_labels != c)
Yes, let's remove this one.

2022-08-04 19:18 UTC, valentyn1boreiko commented on shifthappens/tasks/worst_case/worst_case.py
> +    verbose: bool = True
Ah, true, I forgot about it here - I will change that.

2022-08-04 19:47 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +
```suggestion
    verbose: bool = shifthappens.config.verbose
    probs = None
    labels_type: str = parameter(
        default="val",
        options=("val", "val_clean"),
        description="set the label type either to 50000 or 46044 for the "
        "cleaned labels from [3]",
    )
```

2022-08-04 19:53 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +    verbose: bool = shifthappens.config.verbose
```suggestion
```

2022-08-04 19:53 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +    def _evaluate(self, model: sh_models.Model, verbose=False) -> TaskResult:
```suggestion
    def _evaluate(self, model: sh_models.Model) -> TaskResult:
```

2022-08-04 19:58 UTC, kotekjedi commented on shifthappens/tasks/__init__.py
> +from shifthappens.tasks import worst_case # noqa: F401
```suggestion
from shifthappens.tasks import worst_case  # noqa: F401
```

2022-08-04 21:09 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +
```suggestion
from typing import Union

import numpy as np
import requests
from numpy.core.multiarray import ndarray

import shifthappens.config
from shifthappens import benchmark as sh_benchmark
from shifthappens.data import imagenet as sh_imagenet
from shifthappens.models import base as sh_models
from shifthappens.tasks.base import parameter
from shifthappens.tasks.base import Task
from shifthappens.tasks.metrics import Metric
from shifthappens.tasks.task_result import TaskResult
from shifthappens.tasks.worst_case import worst_case_utils
```

2022-08-04 21:09 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +    superclasses: List[tuple] = None
```suggestion
    superclasses = None
```

2022-08-04 21:09 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +
```suggestion
        self.new_labels = []
```

2022-08-04 21:09 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +        """Saves to a property as a dict the computed predictions and probabilities for the used model"""
```suggestion
        """Saves to a property as a dict the computed predictions and probabilities for the used model"""
        assert self.probs is not None, "probabilities are not initialized"
```

2022-08-04 21:09 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +        if verbose:
```suggestion
        if verbose:
                assert isinstance(self.new_labels, list)
```

2022-08-04 21:16 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +            print(
```suggestion
            assert isinstance(self.new_labels, list)
            print(
```

2022-08-04 21:25 UTC, kotekjedi commented on shifthappens/tasks/worst_case/worst_case.py
> +
```suggestion
from shifthappens.tasks.worst_case import worst_case_utils


```

2022-11-19 10:18 UTC, zimmerrol approved these changes

2022-11-19 10:18 UTC, merged