add evaluation under adversarial patch attack
shift-happens-benchmark/icml-2022 pull request #65
Opened 2022-06-28 00:18 UTC by JindongGu

# Task Description
Add evaluation under adversarial patch attack

## Dataset Creation
Standard ImageNet Validation Dataset

## Evaluation Metrics
Standard Accuracy

## Expected Insights/Relevance
The robustness to patch attack

# Access
No available

## Data
No

## License
No available

2022-07-09 21:59 UTC, stes requested changes
Hi @JindongGu , thanks a lot for your contribution. We are working towards the first release of the benchmark and for this, released our [contribution guide](https://github.com/shift-happens-benchmark/icml-2022/blob/main/CONTRIBUTING.rst) with the aim of unifying the implementation of all contributions.

Please have a look, the required changes should be relatively small and are mostly concerns with placing the files within the package, and adding documentation.

From reviewing your PR, the main required changes are:

- [ ] Place the files into their own package inside the `tasks/` folder (@georgepachitariu )
- [ ] Add a README and optionally citation info
- [ ] We are also looking into the best ways to perform unit or integration tests and would be happy to get some feedback on how this would be most effective for you benchmark. Would it be possible to add a "dry-run/demo" option to the benchmark, and e.g. run it only on a small subset of the data? No immediate action/update is required right now, we are first gathering opinions from all authors on this.

Thanks a lot for your contribution, and please ping me if you have any questions. If you have technical questions, also feel free to ping @kotekjedi who is happy to help with implementation details.

2022-07-09 21:59 UTC, stes commented on examples/imagenet_adv_patch.py
> +class ImageNet_Adv_Patch(Task):
```suggestion
@sh_benchmark.register_task(
    name="ImageNet_Adv_Patch", relative_data_folder="imagenet_val/", standalone=True
)
@dataclasses.dataclass
class ImageNet_Adv_Patch(Task):
```

2022-07-09 21:59 UTC, stes commented on examples/imagenet_adv_patch.py
> +sys.path.append('./')
```suggestion
```

This should be possible to be removed once the changes required via the contribution guide (i.e. placing the code into its own subpackage) are addressed.

2022-07-09 21:59 UTC, stes commented on examples/imagenet_adv_patch.py
> +    sh_benchmark.evaluate_model(ResNet18(device="cuda:0", max_batch_size=8), "../")
This can be removed.
```suggestion
```

2022-07-10 05:55 UTC, stes commented
Hi!

This is an automated report for the documentation coverage of your PR. To provide good user experience for the benchmark, we aim to cover most functions with doc strings, using the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

We would greatly appreciate your help in assuring that docstring coverage is sufficiently high for your contribution.

The current coverage is:
| Name                         |     Total |     Miss |     Cover |     Cover% |
|------------------------------|-----------|----------|-----------|------------|
| imagenet_adv_patch.py        |         3 |        2 |         1 |        33% |
|------------------------------|-----------|----------|-----------|------------|
| TOTAL                        |         3 |        2 |         1 |      33.3% |
RESULT: FAILED (minimum: 80.0%, actual: 33.3%)

You can reproduce this result by running

```
interrogate -v --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method
```

on the files you added to your PR.

2022-08-05 14:43 UTC, kotekjedi commented on examples/imagenet_adv_patch.py
> +import shifthappens.utils as sh_utils
```suggestion
import shifthappens.models.base as sh_models
import shifthappens.data.base as sh_data
import shifthappens.data.torch as sh_data_torch
import shifthappens.utils as sh_utils
```
Should we remove this? These imports are never used.

2022-08-05 14:43 UTC, kotekjedi commented on examples/imagenet_adv_patch.py
> +    name="ImageNet_Adv_Patch", relative_data_folder="imagenet_val/", standalone=True
```suggestion
    name="ImageNet_Adv_Patch", relative_data_folder="imagenet_adv_patch", standalone=True
```
We shouldn't use a path name here which is dependent on imagenet validation path.

2022-08-05 14:43 UTC, kotekjedi commented on examples/imagenet_adv_patch.py
> +        dataset_folder = os.path.join(self.data_root, "./")
Please, update your PR with a current version of the main.
Here you could use `dataset_folder = shifthappens.config.imagenet_validation_path`.

Or even replace whole data loader creation part with `shifthappens.data.inagenet.get_imagenet_validation_loader`.

2022-08-05 14:43 UTC, kotekjedi commented on examples/imagenet_adv_patch.py
> +            exit()
```suggestion
```

2022-08-05 14:43 UTC, kotekjedi commented on examples/imagenet_adv_patch.py
> +        accuracy = all_predicted_labels == np.array(self.ch_dataset.targets)
Here accuracy is an array of True and False values: should we do `accuracy = np.mean(all_predicted_labels == np.array(self.ch_dataset.targets))`

2023-02-06 21:00 UTC, closed without merging