Add ImageNet-M evaluation task
shift-happens-benchmark/icml-2022 pull request #69
Opened 2022-06-30 19:29 UTC by vrv

# Task Description
Add a short and general description of your task here. Ideally, also show some samples of the dataset.

## Dataset Creation
Describe the collection/creation of the images present in this task.

## Evaluation Metrics
Which evaluation metrics does your task use? Why are they relevant?

## Expected Insights/Relevance
Which insights do you expect from testing models on this new task/dataset?

# Access

## Data
Add links to access the data here. 

## License
Do you have the permission to release the images in your task? Is the license of the data and your code compatible with the license of this repository?

2022-06-30 19:47 UTC, vrv commented
FYI I'm continuing to debug why ResNet-18 doesn't get great results, but if you have any other feedback, it's worth taking a look at now.

2022-06-30 20:01 UTC, vrv commented
So I think the problem is:

model.imagenet_validation_result returns structures of length 50000 in an order that matches the Torch data loader.

We have new additional labels on our subset that we're loading in this file, and we index by filename.

We don't know how imagenet_validation_result order maps to filename order, so we can't map the results properly.

The ImageNet Torch DataLoader does not seem to have any indication of the order, so I can't even manually construct this mapping.

Any ideas on what to do here?

2022-06-30 21:59 UTC, vrv commented
Okay, I found a way to use the Torch data loader to create the mapping from filename -> index, now I get

```
    Total ImageNet-M correct: 16
    ImageNet-M accuracy:  0.23529411764705882
```

as hoped!  Please take a look.

2022-07-02 20:23 UTC, vrv commented
(I fixed the isort issue, please feel free to test again!)

2022-07-09 21:46 UTC, stes requested changes
Hi @vrv, thanks a lot for your contribution. We are working towards the first release of the benchmark and for this, released our [contribution guide](https://github.com/shift-happens-benchmark/icml-2022/blob/main/CONTRIBUTING.rst) with the aim of unifying the implementation of all contributions.

Please have a look, the required changes should be relatively small and are mostly concerns with placing the files within the package, and adding documentation.

From reviewing your PR, the main required changes are:

- [ ] Place the files into their own package inside the `tasks/` folder
- [ ] Add a README and optionally citation info
- [ ] We are also looking into the best ways to perform unit or integration tests and would be happy to get some feedback on how this would be most effective for you benchmark. Would it be possible to add a "dry-run/demo" option to the benchmark, and e.g. run it only on a small subset of the data? No immediate action/update is required right now, we are first gathering opinions from all authors on this.

Thanks a lot for your contribution, and please ping me if you have any questions. If you have technical questions, also feel free to ping @kotekjedi who is happy to help with implementation details.

2022-07-09 21:46 UTC, stes commented on examples/imagenet_m.py
> +class ImageNetM(Task):
Could you add a short docstring here?

2022-07-10 05:55 UTC, stes commented
Hi!

This is an automated report for the documentation coverage of your PR. To provide good user experience for the benchmark, we aim to cover most functions with doc strings, using the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

We would greatly appreciate your help in assuring that docstring coverage is sufficiently high for your contribution.

The current coverage is:
| Name                 |       Total |       Miss |       Cover |       Cover% |
|----------------------|-------------|------------|-------------|--------------|
| imagenet_m.py        |           4 |          2 |           2 |          50% |
|----------------------|-------------|------------|-------------|--------------|
| TOTAL                |           4 |          2 |           2 |        50.0% |
RESULT: FAILED (minimum: 80.0%, actual: 50.0%)

You can reproduce this result by running

```
interrogate -v --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method
```

on the files you added to your PR.

2022-07-11 18:00 UTC, vrv commented on examples/imagenet_m.py
> +class ImageNetM(Task):
Done

2022-08-05 11:45 UTC, kotekjedi commented on shifthappens/tasks/__init__.py
> +from shifthappens.tasks import imagenet_m
```suggestion
from shifthappens.tasks import imagenet_m  # noqa: F401
```
Fix to pass mypy test.

2022-08-05 11:45 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +
```suggestion
    prediction was considered a "major" mistake.

```
Fix to pass black test.

2022-08-05 11:45 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +    See the citation file for more information about how the dataset
```suggestion
    See the citation file for more information about how the dataset
```
Fix to pass black test.

2022-08-05 11:45 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +    def setup(self):
```suggestion
    """
    
    def setup(self):
```
Fix to pass black test.

2022-08-05 11:45 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +                im_filename = filename.split("/")[-1]
```suggestion
                im_filename = os.path.normpath(os.path.basename(filename))
```
I believe it is better to use `os.path.basename` instead of `split`, to address the backslash in the path.

2022-08-05 11:45 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +            image_id = int(image_name.split("_")[-1][:-5])
This variable is never used - should we remove it?

2022-08-05 11:45 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +        )
```suggestion
        )
        
```

2022-08-05 16:36 UTC, vrv reviewed
Moved.

2022-08-05 16:36 UTC, vrv commented on shifthappens/tasks/imagenet_m/__init__.py
> +            image_id = int(image_name.split("_")[-1][:-5])
Done.

2022-08-05 16:37 UTC, vrv commented
Thanks for the review, please take a look

2022-08-16 23:53 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +
```suggestion

```

2022-08-16 23:53 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +
```suggestion

```

2022-08-16 23:54 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +
To pass black linter

2022-08-16 23:54 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +
To pass black linter.

2022-08-16 23:58 UTC, kotekjedi commented on shifthappens/tasks/imagenet_m/__init__.py
> +            iif = tv_datasets.ImageFolder(root=imagenet.ImageNetValidationData)
Hi!
Could you please update your branch with the current state of the main, and replace `imagenet.ImageNetValidationData` with `shifthappens.config.imagenet_validation_path`?

2022-11-19 10:15 UTC, merged