Update LICENSE file
shift-happens-benchmark/icml-2022 pull request #73
Opened 2022-07-03 17:09 UTC by stes

We will include all contributors in the license file.

2022-07-06 06:05 UTC, zimmerrol requested changes

2022-07-06 06:05 UTC, zimmerrol commented on LICENSE
> +   required to cite the publications of the benchmarks, tasks and datasets
Should we add that they also need to cite this python package?

2022-07-09 20:41 UTC, stes commented on LICENSE
> +   required to cite the publications of the benchmarks, tasks and datasets
yes, good idea

2022-07-09 20:42 UTC, stes commented on LICENSE
> +   you evaluate and/or adapt for your work.
```suggestion
   If you use this software for academic and research purposes, you are
   required to cite the publications of the benchmarks, tasks and datasets
   you evaluate and/or adapt for your work. Please also cite the software
   directly.
```

2022-07-09 20:44 UTC, zimmerrol approved these changes

2022-07-09 20:52 UTC, merged