Add global configuration options
shift-happens-benchmark/icml-2022 pull request #75
Opened 2022-07-03 17:52 UTC by stes

A proposal for adding global configuration options. Right now I only saw three locations where this might be handy; in the future we might build this out to some hierachical structure where each package gets its own config, but my sense is that this is currently overkill.

The PR adds tests directly that should demonstrate the usecases. In brief, the functionality can be used by simply using

```python
import shifthappens.config
shifthappens.config.verbose
shifthappens.config.imagenet_validation_path
```

etc.

2022-07-03 19:13 UTC, valentyn1boreiko commented
Yes, I agree @stes - I have always been thinking of this API in context of one task only, but for more general cases I'd also prefer to have such a config with verbose and imagenet_validation_path fields.

2022-07-06 06:13 UTC, zimmerrol requested changes

2022-07-06 06:13 UTC, zimmerrol commented on shifthappens/config.py
> +    def get_instance(cls, **init_kwargs):
TODO: Add missing docs.

2022-07-06 06:13 UTC, zimmerrol commented on shifthappens/config.py
> +    imagenet_validation_path: str = "shifthappens/imagenet"
Did you test whether the docstrings for these default values are properly rendered, i.e., in the documentation? I'm asking this since we seemed to use a different syntax that worked with sphinx before.

2022-07-06 06:13 UTC, zimmerrol commented on shifthappens/config.py
> +def __getattr__(key):
Shouldn't this be part of the class?

2022-07-06 06:13 UTC, zimmerrol commented on shifthappens/config.py
> +def get_config(**init_kwargs):
TODO: Add missing docstring.

2022-07-09 20:35 UTC, stes commented
@kotekjedi could you have a look at this and adapt the docs?

2022-07-10 18:07 UTC, kotekjedi commented on shifthappens/config.py
> +def __getattr__(key):
This allows accessing Config attributes easier from other files, e.g.  `import shifthappens.config.cache_directory_path`

2022-07-10 18:57 UTC, zimmerrol requested changes

2022-07-10 18:57 UTC, zimmerrol commented on shifthappens/config.py
> +    1. By setting variables explicitly when getting the instance via get_config()
Make sure the reference to the `get_config` function is correctly rendered in the docs.

2022-07-10 18:57 UTC, zimmerrol commented on shifthappens/config.py
> +        Initializes config with provided arguments. If no arguments were provided,
Let's rather say "if no arguments are provied, a new config will be initialized"

2022-07-10 22:24 UTC, kotekjedi commented
This version has a problem that I don't know how to fix: config fields are duplicated ![image](https://user-images.githubusercontent.com/39771221/178164169-ce776063-49f6-4641-b97a-64019ad1e95e.png)

2022-07-11 12:19 UTC, stes reviewed
Could we aim to provide access through `config.<name>` rather than `config.Config.<name>`? The latter seems overly complicated from a user perspective. I commented a few but not all of these instances.

2022-07-11 12:19 UTC, stes commented on shifthappens/data/imagenet.py
> +    :py:attr:`shifthappens.config.Config.imagenet_validation_path` must be specified.
```suggestion
    :py:attr:`shifthappens.config.imagenet_validation_path` must be specified.
```

2022-07-11 12:19 UTC, stes commented on shifthappens/data/imagenet.py
> +        "shifthappens.config.Config.cache_directory_path is not specified."
```suggestion
        "shifthappens.config.cache_directory_path is not specified."
```

2022-07-11 12:19 UTC, stes commented on shifthappens/data/imagenet.py
> +    :py:attr:`shifthappens.config.Config.imagenet_validation_path` must be specified as
```suggestion
    :py:attr:`shifthappens.config.imagenet_validation_path` must be specified as
```

2022-07-11 12:19 UTC, stes commented on shifthappens/data/imagenet.py
> +    well as :py:attr:`shifthappens.config.Config.cache_directory_path`.
```suggestion
    well as :py:attr:`shifthappens.config.cache_directory_path`.
```

2022-07-11 12:19 UTC, stes commented
> This version has a problem that I don't know how to fix: config fields are duplicated ![image](https://user-images.githubusercontent.com/39771221/178164169-ce776063-49f6-4641-b97a-64019ad1e95e.png)

This is fine for now. We can later configure sphinx appropriately, this is a docs generation issue rather than sth about the code docs.

2022-07-11 12:20 UTC, stes commented on shifthappens/config.py
> +def __getattr__(key):
@zimmerrol no it was intentionally implemented this way to provide easy access without having to write `config.Config` when accessing attributes.

2022-07-11 12:24 UTC, stes commented
Hi @kotekjedi largest issue here is that for the user all attributes should be accessible through `shifthappens.config` (unless @zimmerrol thinks it should be implemented differently, but in my opinion this is the cleanest way for the end user later on).

Once @zimmerrol gives a :+1: , could you adapt the docs and make sure that user-facing, all attributes are accessible as `shifthappens.config.<...>`? The required change in ``shifthappens.config`` is then to dynamically adapt the `__docs__` string with the individual doc strings for each of the attributes (or by adding these manually, whatever you prefer).

2022-07-11 17:27 UTC, kotekjedi commented on shifthappens/data/imagenet.py
> +    :py:attr:`shifthappens.config.Config.imagenet_validation_path` must be specified.
I agree with you, that it seems better to allow access through `config.<name>`. But I think giving a `config.Config.<name>` name in the error message is better. 
My point of view is that like this, it is easier to find what caused the problem - some field in `config.Config`. Otherwise (at least for me), it takes some time to realize that we are allowing access in this manner `config.<name>`, and the problem is inside Config class fields.

2022-07-17 09:34 UTC, zimmerrol commented
@kotekjedi Can you please update this PR as suggested above? Thanks!

2022-07-18 08:11 UTC, zimmerrol approved these changes
LGTM

2022-07-18 08:11 UTC, merged