Add contributor statement
shift-happens-benchmark/icml-2022 pull request #78
Opened 2022-07-03 19:10 UTC by stes

Please review. Once we agreed on the wording and merged this, we should link it in all open contributions and make sure all tasks are following this scheme. Right now, there is no consistent way the tasks are added to the package.

2022-07-07 06:49 UTC, zimmerrol requested changes

2022-07-07 06:49 UTC, zimmerrol commented on CONTRIBUTING.rst
> +a doc string to the top of your ``__init__.py`` file, which is used to auto-generate
The authors should also autoload their new package to the `shifthappens/tasks/__init__.py` such that the registration code of their tasks is triggered.

2022-07-07 06:52 UTC, zimmerrol commented on CONTRIBUTING.rst
> +a doc string to the top of your ``__init__.py`` file, which is used to auto-generate
Maybe something like "Also, you need to add a import of your package the to the `shifthappens/tasks/__init__.py` file, e.g. `from shifthappens.tasks.task_name import task_name`.

2022-07-07 06:53 UTC, zimmerrol commented on CONTRIBUTING.rst
> +You can add as many utility or helper scripts as possible.
possible -> necessary

2022-07-07 07:36 UTC, zimmerrol requested changes

2022-07-07 07:36 UTC, zimmerrol commented on CONTRIBUTING.rst
> +    from shifthappens.task import your_task
It should be tasks not task, no?

2022-07-09 20:31 UTC, stes commented on CONTRIBUTING.rst
> +    from shifthappens.task import your_task
```suggestion
    from shifthappens.tasks import your_task
```

2022-07-09 20:33 UTC, stes commented on CONTRIBUTING.rst
> +
```suggestion

We are currently looking into options for how to setup unit and integration tests and will setup this note accordingly. If you have suggestions, feel free to create a PR for adapting this contribution guide.

```

2022-07-09 20:40 UTC, zimmerrol approved these changes

2022-07-09 20:48 UTC, merged