Add imagenet_cartoon and imagenet_drawing
shift-happens-benchmark/icml-2022 pull request #80
Opened 2022-07-09 08:20 UTC by tiagosalvador

# Task Description
Two datasets for benchmarking machine learning robustness against domain shifts, based on the ImageNet dataset and using using a GAN framework and simple image processing.

<img width="1029" alt="examples" src="https://user-images.githubusercontent.com/38894497/178097450-8b888907-d2b9-46f0-bfb7-c99700a92b1e.png">
Several examples of ImageNet images (top) and their respective ImageNet-Cartoon (middle) and ImageNetDrawing (bottom) versions.

## Dataset Creation
Images are taken from the ImageNet dataset and the transformed into cartoon using the GAN framework proposed by [1] and into drawing using the simple image processing described in [2].

[1] Wang, X. and Yu, J. Learning to cartoonize using white-box cartoon representations. In _Proceedings of the IEEE/CVF
Conference on Computer Vision and Pattern Recognition (CVPR)_, June 2020.
[2] Lu, C., Xu, L., and Jia, J. Combining Sketch and Tone for Pencil Drawing Production. In Asente, P. and Grimm, C.
(eds.), _International Symposium on Non-Photorealistic Animation and Rendering_. The Eurographics Association, 2012. ISBN 978-3-905673-90-6. doi: 10.2312/PE/NPAR/NPAR12/065-073.

## Evaluation Metrics
Robust accuracy: correct classification of the transformed images.

## Expected Insights/Relevance
The accuracy of pretrained ImageNet models decreases significantly on the proposed datasets.

## Access
We release the dataset on Zenodo (https://zenodo.org/record/6801109), as well as the code to generate the two datasets  (https://github.com/oberman-lab/imagenet-shift).

## Data
The dataset is hosted on Zenodo (https://zenodo.org/record/6801109).

## License
We released the data with the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/legalcode).

2022-07-09 21:06 UTC, stes requested changes
Hi @tiagosalvador , thanks a lot for your contribution. We are working towards the first release of the workshop and for this, released our [contribution guide](https://github.com/shift-happens-benchmark/icml-2022/blob/main/CONTRIBUTING.rst) with the aim of unifying the implementation of all contributions.

Please have a look, the required changes should be relatively small and are mostly concerns with placing the files within the package, and adding documentation.

From reviewing your PR, the main required changes are:

- [ ] Place the files directly in the package instead of the example order
- [ ] Add a README and optionally citation info
- [ ] Add more description to your python files (to the docstring -- the documentation will be auto generated from this)

Thanks a lot for your contribution, and please ping me if you have any questions. If you have technical questions, also feel free to ping @kotekjedi who is happy to help with implementation details.

2022-07-10 05:55 UTC, stes commented
Hi!

This is an automated report for the documentation coverage of your PR. To provide good user experience for the benchmark, we aim to cover most functions with doc strings, using the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

We would greatly appreciate your help in assuring that docstring coverage is sufficiently high for your contribution.

The current coverage is:
| Name                     |      Total |      Miss |      Cover |      Cover% |
|--------------------------|------------|-----------|------------|-------------|
| imagenet_cartoon.py      |          3 |         2 |          1 |         33% |
| imagenet_drawing.py      |          3 |         2 |          1 |         33% |
|--------------------------|------------|-----------|------------|-------------|
| TOTAL                    |          6 |         4 |          2 |       33.3% |
RESULT: FAILED (minimum: 80.0%, actual: 33.3%)

You can reproduce this result by running

```
interrogate -v --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method
```

on the files you added to your PR.

2022-07-17 09:31 UTC, zimmerrol requested changes
Thanks for this PR! Once the examples/* files are removed (since you moved them, as requested, to the shifthappens/tasks package), we should be good to merge this PR.

2022-07-18 15:02 UTC, kotekjedi commented on shifthappens/tasks/imagenet_cartoon/__init__.py
> +
```suggestion

```

2022-07-18 15:02 UTC, kotekjedi commented on shifthappens/tasks/imagenet_cartoon/__init__.py
> +    """
```suggestion
    """
    
```

2022-07-18 15:07 UTC, kotekjedi commented
Hi Tiago!
My name is Alexander Panfilov; I am a student research assistant working on supporting the project. I reviewed the PR and left some comments - two are about paths, and the other is to pass black formatter.

2022-07-18 15:21 UTC, tiagosalvador commented on shifthappens/tasks/imagenet_drawing/__init__.py
> +                    url, self.data_root, md5, file_name
Yes, it should.

2022-07-18 15:21 UTC, tiagosalvador commented on shifthappens/tasks/imagenet_cartoon/__init__.py
>              for file_name, url, md5 in self.resources:
Yes, it should.

2022-07-18 15:21 UTC, tiagosalvador commented
Hi Alexander! I made the necessary changes. Thanks for reviewing it!

2022-11-19 10:19 UTC, merged