[Examples moved]
shift-happens-benchmark/icml-2022 pull request #85
Opened 2022-07-11 11:35 UTC by kotekjedi

* examples/ -> tasks/
* raccoons_OOD.py -> raccoons_ood.py

2022-07-11 11:36 UTC, kotekjedi commented
I think that [#75](https://github.com/shift-happens-benchmark/icml-2022/pull/75) should be merged first, and then we can update paths here as well.

2022-07-11 12:08 UTC, stes requested changes
Thanks @kotekjedi .

According to the contribution guide you can move the contents of imagenet_c.py directly into the `__init__.py`, or at least make sure in the `__init__.py` that the task is registered. (maybe the latter option is better)

2022-07-11 12:08 UTC, stes commented on shifthappens/tasks/imagenet_c/README.rst
> +
```suggestion
```

2022-07-11 12:08 UTC, stes commented on shifthappens/tasks/imagenet_r/imagenet_r.py
> +                    url, self.data_root, None, file_name
Could you add the hash? If you dont want to recompute, they are probably also published somewhere.

2022-07-11 12:08 UTC, stes commented on shifthappens/tasks/raccoons_ood/README.rst
> +
```suggestion
```

2022-07-11 12:08 UTC, stes commented on shifthappens/tasks/raccoons_ood/README.rst
> +and can be found at https://github.com/datitran/raccoon_dataset.
@j-cb do you want to extend the readme for this task? (just propose as a change to this PR).

2022-07-15 22:26 UTC, zimmerrol commented
@kotekjedi Once you have fixed the merge conflcits and fixed the hash, we can merge this PR.

2022-07-16 14:17 UTC, kotekjedi commented
Done. I updated the cash (for me, it was an upper-case problem).

2022-07-16 20:22 UTC, zimmerrol commented
@kotekjedi Can you please update the READMEs for ImageNet-C/R based in the current docstring of the classes & modules (e.g., the references to the papers must be included).

2022-07-17 09:25 UTC, zimmerrol approved these changes
LGTM

2022-07-17 09:26 UTC, merged