Add Semantic Shift Benchmark
shift-happens-benchmark/icml-2022 pull request #93
Opened 2022-07-17 22:06 UTC by sgvaze

# Task Description
We propose the Semantic Shift Benchmark suite (SSB) for open-set recognition and related tasks (e.g category discovery, out-of-distribution detection etc.). We define class splits from ImageNet-21K which are 'unseen' with respect to categories from ImageNet-1K.

Below, we show open-set classes (from ImageNet-21K) in dotted lines and their **closest counterparts** (from ImageNet-1K) in solid lines. The 'Hard' open-set classes have significantly more similar closed-set counterparts.

![ssb_imagenet](https://user-images.githubusercontent.com/33980832/179426438-0de9efd1-87ad-4d2c-b6f2-ce77fca9e48c.png)

## Dataset Creation
We mine open-set classes from [ImageNet-21K-P](https://github.com/Alibaba-MIIL/ImageNet21K), structuring the splits based on semantic distance in the WordNet hierarchy.

## Expected Insights/Relevance
The SSB is intended to isolate semantic novelty from other forms of distributional shifts. We structure open-set classes based on their semantic distance to the closed-set (the ImageNet-1K classes). Specifically, we provide 'seen' and 'unseen' class splits, where the 'unseen' classes are divided into 'Easy' and 'Hard'. Harder examples are more visually and semantically similar to the 'seen' classes.

## Evaluation Metrics
The unseen classes can be used for multiple downstream tasks (e.g category discovery and OoD detection). We evaluate open-set recognition performance with AUROC.

## Data
We use classes from the ImageNet-21K-P dataset, which can be downloaded and pre-processed following instructions [here](https://github.com/Alibaba-MIIL/ImageNet21K).

## License
ImageNet licence

2022-07-19 05:14 UTC, stes requested changes
Thanks for the contribution!

A few minor comments to remove uncommented code --- also it might be useful to run the pre-commit hooks to format code etc., but @kotekjedi can also help with this and format the PR.

2022-07-19 05:14 UTC, stes commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +#         return img, label, uq_idx
```suggestion
```

remove if not needed?

2022-07-19 05:14 UTC, stes commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +print('Hello')
```suggestion
```

2022-07-19 05:14 UTC, stes commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +        # ])
```suggestion
```

remove if not needed?

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/__init__.py
> +)
```suggestion

```
Let's move the decorator to the `semantic_shift_benchmark.py` file.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +#         return img, label, uq_idx
```suggestion

```

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +import torchvision
```suggestion
```
This import is never used.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +import torch
```suggestion
```
This import is never used.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +from shifthappens import benchmark as sh_benchmark
```suggestion
```
This import is never used.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +sh_benchmark.register_task(
Why do we need second task registration here?

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +def get_imagenet_ssb_datasets(test_transform, imagenet21k_root, osr_split_path):
I would suggest passing .pkl here directly, smth like this:
```
def get_imagenet_ssb_datasets(test_transform, imagenet21k_root, osr_split):

    easy_wnids = osr_split['easy_i21k_classes']
    hard_wnids = osr_split['hard_i21k_classes']

```

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +import torch
```suggestion
```
This import is never used.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +import shifthappens.utils as sh_utils
```suggestion
```
This import is never used.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +from shifthappens.tasks.ssb import osr_split_path
I would suggest removing this and add .pkl loading inside the class

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +
```suggestion
import requests

PKL_URL = "https://github.com/sgvaze/osr_closed_set_all_you_need/raw/main/data/open_set_splits/imagenet_osr_splits_winter21.pkl"


@sh_benchmark.register_task(name="SSB", relative_data_folder="ssb", standalone=True)
```

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +    resource = (
I would suggest removing this

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +
Let's add downloading here

```
        pickle_path = os.path.join(self.data_root, "imagenet_osr_splits_winter21.pkl")
        if not os.path.exists(pickle_path):
            os.makedirs(self.data_root, exist_ok=True)
            pickle_file = requests.get(PKL_URL)
            open(pickle_path, "wb").write(pickle_file.content)

        self.osr_split = pickle.load(open(pickle_path, "rb"))

        imagenet_21k_root = os.path.join(self.data_root, "imagenet21k_resized_new")

```

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +        std = (0.229, 0.224, 0.225)
```suggestion
```
This is never used.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +            self.assert_data_downloaded(imagenet_21k_root)
I would suggest passing here loaded .pkl:
` assert self.assert_data_downloaded(self.osr_split, imagenet_21k_root)
`

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +                                                                        test_transform=test_transform)
```
        dataset_out_easy, dataset_out_hard = get_imagenet_ssb_datasets(
            test_transform=test_transform,
            imagenet21k_root=imagenet_21k_root,
            osr_split=self.osr_split,
        )
```
I would suggest passing .pkl here.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +                precomputed_info = pickle.load(handle)
```
    def assert_data_downloaded(osr_split, imagenet21k_root):
        try:
            easy_wnids = osr_split["easy_i21k_classes"]
            hard_wnids = osr_split["hard_i21k_classes"]
            all_wnids = easy_wnids.tolist() + hard_wnids

            dataset_folder = os.path.join(imagenet21k_root, "val")
```
Let's remove loading from here.

2022-08-08 17:55 UTC, kotekjedi commented on shifthappens/tasks/ssb/semantic_shift_benchmark.py
> +    def assert_data_downloaded(imagenet21k_root):
Should we maybe remove this function to `imagent_ssb.py` ?

2022-08-08 17:56 UTC, kotekjedi commented
Should we maybe remove .png file from this PR?

2022-08-20 17:42 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +def get_imagenet_osr_class_splits(imagenet21k_class_to_idx, precomputed_split_dir, osr_split='Easy'):
This function is never used - do we need it?

2022-08-20 17:42 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +def subsample_classes(dataset, include_classes=list(range(1000))):
This function is never used - do we need it?

2022-08-20 17:42 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +def get_train_val_split(train_dataset, val_split=0.2):
This function is never used - do we need it?

2022-08-20 17:42 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +def get_equal_len_datasets(dataset1, dataset2):
This function is never used - do we need it?

2022-08-20 21:16 UTC, kotekjedi commented
Hi Sagar! I refactored your code a bit, so it is now correctly integrated with our API. Could you please check the current version and say if everything is OK?

Also, it would be nice if you could add docstrings to `semantic_shift_benchmark.py `and remove unused functions from `imagenet_ssb.py` if they are unnecessary.

I would also like to clarify what version of the dataset task uses? Fall 11 Version or Winter 21 Version? I wrote a couple of asserts assuming that it is a Winter 21 Version, but if not, I will adapt the code. I think we should also note this in the docstring.

2022-08-20 21:20 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +        print(len(samples))
```suggestion
```

2022-08-20 21:20 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +def get_imagenet_osr_class_splits(
This function is never used - do we need it?

2022-08-20 21:20 UTC, kotekjedi commented on shifthappens/tasks/ssb/imagenet_ssb.py
> +def subsample_classes(dataset, include_classes=range(1000)):
This function is never used - do we need it?

2022-09-13 01:54 UTC, sgvaze commented
Hi @kotekjedi - thanks for your help! I have made the requested changes and pushed again :)

2022-11-17 21:10 UTC, zimmerrol approved these changes

2022-11-17 21:12 UTC, zimmerrol approved these changes

2022-11-17 21:13 UTC, merged