ObjectNet
shift-happens-benchmark/icml-2022 pull request #99
Opened 2022-08-12 09:13 UTC by kotekjedi

ObjectNet task implementation.

2022-08-13 11:15 UTC, zimmerrol requested changes
Small changes requested, but overall the code looks good! Can you please also add a CITATION.cff (see https://github.com/shift-happens-benchmark/icml-2022/pull/60/files#diff-cff7599d4e8605d087d90de757b2c4c93644510cd58ad270c070ce65ce1e2cfa for an example)

2022-08-13 11:15 UTC, zimmerrol commented on shifthappens/tasks/objectnet/objectnet.py
> +JSON_URL = "https://raw.githubusercontent.com/abarbu/objectnet-template-tensorflow/master/mapping_files/imagenet_id_to_objectnet_id.json"
Let's move this also to the class definition, like the `resources` field.

2022-08-13 11:15 UTC, zimmerrol commented on shifthappens/tasks/objectnet/objectnet.py
> +                tv_transforms.Pad(-2),
Why do we apply this padding here?

2022-08-13 11:15 UTC, zimmerrol commented on shifthappens/tasks/objectnet/objectnet_utils.py
> +# udapted from https://github.com/pytorch/vision/blob/0cba9b7845795d6be7b164037461ea6e9265f6a2/torchvision/datasets/utils.py
typo

2022-08-13 11:15 UTC, zimmerrol commented on shifthappens/tasks/objectnet/objectnet_utils.py
> +    This is required for handling empty folders that cannot be mapped classes in ImageNet.
typo: cannot be mapped to classes

2022-08-13 11:15 UTC, zimmerrol commented on shifthappens/tasks/objectnet/objectnet_utils.py
> +        """Rejects the folders that cannot be mapped classes in ImageNet."""
typo: cannot be mapped to

2022-08-13 13:14 UTC, kotekjedi commented on shifthappens/tasks/objectnet/objectnet.py
> +                tv_transforms.Pad(-2),
Every ObjectNet image has a tiny red border across it. This is written on the ObjectNet website "We provide ObjectNet with a 1 pixel red border around each image which must be removed before performing inference. The ObjectNet license requires that if you post images from ObjectNet to the web, you include this border. Any time you see an image with a solid 1 pixel red border, that's an indication it's in someone's test set and you should be careful about training on it. "

Although the authors stated that it is only a 1-pixel border I visualized the transformed image with a `tv_transforms.Pad(-1)`, and it still has this border, so I use `tv_transforms.Pad(-2)` here.

2022-08-13 14:33 UTC, kotekjedi commented on shifthappens/tasks/objectnet/objectnet.py
> +        "/imagenet_id_to_objectnet_id.json "
```suggestion
        "/imagenet_id_to_objectnet_id.json"
```

2022-08-13 18:02 UTC, kotekjedi commented on shifthappens/tasks/objectnet/objectnet_utils.py
> +    This is required for handling empty folders that cannot be mapped to
```suggestion
    This is required for handling folders that cannot be mapped to
```

2022-11-17 21:01 UTC, zimmerrol approved these changes

2022-11-17 21:02 UTC, merged